In [2]:
import tensorflow as tf
import numpy as np

In [6]:
x = np.array([1,4,2,5,6])
data_set = tf.data.Dataset.from_tensor_slices(x)
data_set

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [8]:
for elem in data_set:
    print(elem)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [10]:
it = iter(data_set)

In [14]:
print(next(it).numpy())

4


import random

def get_random():
    return random.randint(1, 10)

rand_iter = iter(get_random, 7)  # تا زمانی که مقدار ۷ بازگردانده شود اجرا می‌شود
for num in rand_iter:
    print(num)


In [26]:
x = tf.random.uniform([200,10])
data_set = tf.data.Dataset.from_tensor_slices(x)

In [28]:
for index , elem in enumerate(data_set):
    print(elem)
    if index>10:
        break

tf.Tensor(
[0.83546686 0.0850662  0.42021215 0.53862894 0.50977254 0.1979394
 0.8875015  0.21667778 0.5281631  0.6082097 ], shape=(10,), dtype=float32)
tf.Tensor(
[0.85138285 0.9471897  0.30255556 0.16030431 0.71925235 0.5009254
 0.80523443 0.55710506 0.9268421  0.7771517 ], shape=(10,), dtype=float32)
tf.Tensor(
[0.494112   0.94781494 0.9725952  0.27592337 0.84762967 0.14473999
 0.11718678 0.25622106 0.79975116 0.27822566], shape=(10,), dtype=float32)
tf.Tensor(
[0.253201   0.410213   0.7844596  0.85242045 0.01158249 0.95990086
 0.8557637  0.35646546 0.69082344 0.3075106 ], shape=(10,), dtype=float32)
tf.Tensor(
[0.99278414 0.9688184  0.43105042 0.7198936  0.87458    0.7800734
 0.6052849  0.8423253  0.34523296 0.8681675 ], shape=(10,), dtype=float32)
tf.Tensor(
[0.07619727 0.45325434 0.30406845 0.03336167 0.880865   0.99393475
 0.16819763 0.03378916 0.9737309  0.42980433], shape=(10,), dtype=float32)
tf.Tensor(
[0.24762893 0.33553636 0.12829363 0.85681057 0.77948785 0.43666804
 0.2808

In [37]:
data_set.element_spec

TensorSpec(shape=(10,), dtype=tf.float32, name=None)

In [42]:
y= tf.random.uniform([200], maxval=2 , dtype= tf.int32)

In [44]:
data_set = tf.data.Dataset.from_tensor_slices((x,y))

In [46]:
data_set.element_spec

(TensorSpec(shape=(10,), dtype=tf.float32, name=None),
 TensorSpec(shape=(), dtype=tf.int32, name=None))

In [48]:
for i , (x,y) in enumerate(data_set):
    print (f' x{i} is {x} and y is {y}')
    if i >5 :
        break

 x0 is [0.83546686 0.0850662  0.42021215 0.53862894 0.50977254 0.1979394
 0.8875015  0.21667778 0.5281631  0.6082097 ] and y is 0
 x1 is [0.85138285 0.9471897  0.30255556 0.16030431 0.71925235 0.5009254
 0.80523443 0.55710506 0.9268421  0.7771517 ] and y is 1
 x2 is [0.494112   0.94781494 0.9725952  0.27592337 0.84762967 0.14473999
 0.11718678 0.25622106 0.79975116 0.27822566] and y is 0
 x3 is [0.253201   0.410213   0.7844596  0.85242045 0.01158249 0.95990086
 0.8557637  0.35646546 0.69082344 0.3075106 ] and y is 1
 x4 is [0.99278414 0.9688184  0.43105042 0.7198936  0.87458    0.7800734
 0.6052849  0.8423253  0.34523296 0.8681675 ] and y is 1
 x5 is [0.07619727 0.45325434 0.30406845 0.03336167 0.880865   0.99393475
 0.16819763 0.03378916 0.9737309  0.42980433] and y is 0
 x6 is [0.24762893 0.33553636 0.12829363 0.85681057 0.77948785 0.43666804
 0.2808286  0.23190498 0.9969801  0.47922242] and y is 0


In [50]:
x = tf.random.uniform([200,10])
y = tf.random.uniform([200],maxval=2 , dtype=tf.int32)
d_x = tf.data.Dataset.from_tensor_slices(x)
d_y = tf.data.Dataset.from_tensor_slices(y)

In [53]:
print(d_x.element_spec)
print(d_y.element_spec)

TensorSpec(shape=(10,), dtype=tf.float32, name=None)
TensorSpec(shape=(), dtype=tf.int32, name=None)


In [57]:
ds = tf.data.Dataset.zip((d_x,d_y))

In [59]:
ds.element_spec

(TensorSpec(shape=(10,), dtype=tf.float32, name=None),
 TensorSpec(shape=(), dtype=tf.int32, name=None))

In [61]:
for x , y in ds.take(10):
    print (f' x is {x} and y is {y}')

 x is [0.05480599 0.48157954 0.59991086 0.01540196 0.04406714 0.97598875
 0.10218191 0.31618714 0.4023837  0.11394906] and y is 0
 x is [0.14281368 0.69415855 0.0314424  0.6646273  0.9935677  0.13390565
 0.31064916 0.16069269 0.6564995  0.07574069] and y is 0
 x is [0.7853544  0.66077864 0.14747989 0.17897487 0.08568799 0.41381586
 0.7656847  0.82443964 0.22755075 0.9643407 ] and y is 0
 x is [0.36076403 0.11808968 0.67529416 0.20803237 0.7838961  0.49267125
 0.89606917 0.25335646 0.5320978  0.855016  ] and y is 0
 x is [0.6203667  0.04428828 0.8960041  0.27032125 0.40123582 0.80973697
 0.02510369 0.82592976 0.8676882  0.6697124 ] and y is 0
 x is [0.6946014  0.70405805 0.4209509  0.18778133 0.19802868 0.23751032
 0.4461156  0.45761704 0.31633735 0.6005223 ] and y is 0
 x is [0.8086268  0.9661863  0.9461007  0.78108037 0.77155674 0.89198613
 0.12573326 0.7773937  0.65394104 0.6324147 ] and y is 1
 x is [0.01286089 0.8508458  0.22929358 0.15828669 0.00632775 0.755587
 0.20410395 0.25558

In [65]:
x =  tf.range(5)
print(x)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


In [67]:
ds =  tf.data.Dataset.from_tensor_slices(x)

In [69]:
for elem in ds:
    print(elem)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [71]:
ds = ds.shuffle(buffer_size=5)

In [73]:
for elem in ds:
    print(elem)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [76]:
ds = tf.data.Dataset.from_tensor_slices(x)

In [78]:
ds= ds.repeat(2)
for elem in ds:
    print(elem)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [80]:
ds = tf.data.Dataset.from_tensor_slices(x)

In [82]:
ds = ds.shuffle(buffer_size=5)
ds= ds.repeat(2)
for elem in ds:
    print(elem)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [131]:
x = tf.range(100)
ds = tf.data.Dataset.from_tensor_slices(x)

In [105]:
for elem in ds.take(5):
    print(elem)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [109]:
ds_b = ds.batch(20)
for elem in ds_b.take(5):
    print(elem)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19], shape=(20,), dtype=int32)
tf.Tensor([20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39], shape=(20,), dtype=int32)
tf.Tensor([40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59], shape=(20,), dtype=int32)
tf.Tensor([60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79], shape=(20,), dtype=int32)
tf.Tensor([80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99], shape=(20,), dtype=int32)


In [149]:
ds_s = ds.shuffle(buffer_size=15,seed=1, reshuffle_each_iteration=False)
ds_b = ds_s.batch(20)
for elem in ds_b.take(5):
    print(elem)

tf.Tensor([13 14  9  1  4  6  0 18  2 23 20 17  3 26 15 27 10  8 29  7], shape=(20,), dtype=int32)
tf.Tensor([30 28 24 31 34 11  5 12 42 39 16 44 36 35 38 33 37 21 32 41], shape=(20,), dtype=int32)
tf.Tensor([43 53 56 54 45 58 48 25 47 22 40 63 46 66 50 65 61 52 51 71], shape=(20,), dtype=int32)
tf.Tensor([49 59 72 75 60 79 19 64 80 70 74 73 78 67 69 84 57 87 82 91], shape=(20,), dtype=int32)
tf.Tensor([85 94 77 88 90 86 68 95 89 92 96 55 97 99 81 83 98 62 93 76], shape=(20,), dtype=int32)
